### ISSUE TITLE
no zip file for windows

### ISSUE THREAD

**Issue by DaliJarboui** [kusterlab/picked_group_fdr#1]
could not find the PickedGroupFDR_GUI_windows.zip . or any .exe file
is the version missing or not yet released

**Comment by MatthewThe** [comment]
The latest releases do not have the GUI built yet. The last release with a GUI is https://github.com/kusterlab/picked_group_fdr/releases/tag/rel-0-02-0

I will try to automatically build the GUI for every release, but haven't had the time to do this yet.

**Comment by MatthewThe** [comment]
Automatic GUI building for releases added (#2)
