### ISSUE TITLE
Question about scoreType...

### ISSUE THREAD

**Issue by marioernestovaldes** [kusterlab/picked_group_fdr#3]
Hello there! First of all, thanks for developing this wonderful tool... it has been really helpful :)

I have a quick question: I have been using the Picked Protein Group FDR as recommended:

```python
label = "Picked Protein Group FDR"

scoreType = "bestPEP"
grouping = "rescued_subset"
sharedPeptides = "discard"
pickedStrategy = "picked_group"
```

however, I wonder if I could replace `scoreType = "bestPEP"` with `scoreType = "multPEP"` That way, it will compute protein group scores by multiplication of PEPs (already corrected by Percolator in my case, and as suggested in your paper) instead of selecting the best PEP.

I see in the main manuscript you mentioned that using `multPEP` could decrease the number of identified protein groups at 1% protein group-level FDR for the 100% peptide-level FDR cutoff compared to the default 1% peptide-level FDR cutoff. However, if I used the default 1% for the peptide-level FDR cutoff, could we get more protein groups using `multPEP`?

Thanks in advance for your time...

Mario

**Comment by MatthewThe** [comment]
Hi Mario,

Yes, you can definitely try that and it sometimes performs (slightly) better than bestPEP.
However, for large experiments bestPEP did seem to perform better in general.

**Comment by marioernestovaldes** [comment]
Great! thanks for your prompt reply :)

Mario
